### ISSUE TITLE
Can I load other base map services?

### ISSUE THREAD

**Issue by lvlongcheng** [CesiumGS/cesium-unity#151]
Can I load offline map base service in unity？

**Comment by kring** [comment]
Cesium for Unity supports Tile Map Service (TMS) and Web Map Service (WMS). Or you can upload a GeoTIFF or similar to Cesium ion and it will tile it for you. If you would like to discuss further, please post to the [community forum](https://community.cesium.com/c/cesium-for-unity/13). We use github issues for bug reports and feature requests.

**Comment by lvlongcheng** [comment]
Can you tell me where I can use TMS or WMS services instead of using the services in Cesium ion？

**Comment by kring** [comment]
If you're asking where to find such services to use, I don't know. You'll have to source them yourself for the area you're interested in. If you're asking where to put them in Cesium for Unreal once you have them, I can help with that: add a component to the Cesium3DTileset of the appropriate type (`CesiumTileMapServiceRasterOverlay` or `CesiumWebMapServiceRasterOverlay`) and set its properties appropriately.
