### ISSUE TITLE
Add error message for when Unity isn't connected to Cesium Ion 

### ISSUE THREAD

**Issue by DanielArnett** [CesiumGS/cesium-unity#153]
As seen in #152, there's an obscure message when it fails to connect to Cesium Ion. Perhaps we can add error checking for this at some point.

**Comment by j9liu** [comment]
Hi @DanielArnett,

This seems like a bug -- Cesium components should work even if Unity isn't connected to Cesium ion. If you sign out of Cesium ion, does it stop working? If you start the editor with Cesium ion signed out, does this same error get thrown? Or did this only happen the first time you opened Unity?

**Comment by DanielArnett** [comment]
I'll sign out and try again.

**Comment by j9liu** [comment]
Hi @DanielArnett,

I'm going to close this issue for inactivity, but please reopen if you continue to see the issue on your end. Thanks!
