### ISSUE TITLE
Support 3DTilesets on disk: TilesetJsonLoader.cpp sets the tilesetJsonUrl to the baseUrl causing 3DTilesets on disk to fail

### ISSUE THREAD

**Issue by ZackOfAllTrades** [CesiumGS/cesium-unity#166]
Given an example of a 3DTileset on disk, you must set the url of the C# Cesium3DTileset component to the tileset.json path for the TilesetJsonLoader to properly load the json file, for example C:/MapData/3DTilesetExample/tileset.json

This is the only way to get the tileset to correctly load, however in the parseTilesetJson function inside TilesetJsonLoader this tilesetJsonUrl becomes the baseUrl including the tileset.json part, later inside Uri.cpp the call to uriParseSingleUriA() fails " Could not parse the base, so just use the relative directly and hope for the best.", presumably because of the tileset.json on the end (Uri.h is very difficult to read).

I would expect that if the Cesium3DTileset component url is going to be set as the base url then we should enter in the base url and not the path to the tileset.json, so in this case I would set it to C:/MapData/3DTilesetExample/ and the TilesetJsonLoader would append tileset.json or layer.json to that, this would solve the issue.

Please let me know if I'm using this wrong!

**Comment by kring** [comment]
@ZackOfAllTrades you're hitting that "hope for the best" case because `C:/MapData/3DTilesetExample/tileset.json` is not a valid URL. Does it work to use a file URL instead? For example: `file:///C:/MapData/3DTilesetExample/tileset.json`

**Comment by ZackOfAllTrades** [comment]
The problem of having to have the tileset.json as part of the url still remains an issue, inside TileContentManager.cpp ln:644 we take the url from the completed tileset.json request and set it as the base url. This means that this url must be the full path to the tileset.json "C:/MapData/3DTilesetExample/tileset.json". Adding the file:// protocol does not change this, it still fails as the baseUrl is set to "C:/MapData/3DTilesetExample/tileset.json", even if it didnt fail the relative urls would be wrong "C:/MapData/3DTilesetExample/tileset.json/4/0/0/0.subtree", 

what I would expect is we would set the url to the baseUrl "C:/MapData/3DTilesetExample" and on ln 632 of TileContentManager.cpp where we make our tileset.json request we would append "tileset.json" to that

**Comment by kring** [comment]
No, with URLs, if you resolve `4/0/0/0.subtree` relative to `file:///c:/MapData/3DTilesetExample/tileset.json`, you get `file:///c:/MapData/3DTilesetExample/4/0/0/0.subtree`. Because the URL doesn't end with a slash, it is treated as a file, not a directory. If the base URL were `file:///c:/MapData/3DTilesetExample`, then the resolution would be wrong (it would yield `file:///c:/MapData/4/0/0/0.subtree`). Though a base URL of `file:///c:/MapData/3DTilesetExample/` would work fine. Did you try it, or are you only assuming it doesn't work?

**Comment by ZackOfAllTrades** [comment]
I would never just assume. The problem ended up being the Uri.cpp resolve function fails to parse when the url uses escaped backslashes, which is the default output of the C# System.IO.FileInfo and System.IO.DirectoryInfo , for example: 
C:\\MapData\\3DTilesetExample\\tileset.json, no file:// protocol was necessary. 

Perhaps it would make since to sanitize the url to save time for the next person?  
std::replace(tilesetUrl.begin(), tilesetUrl.end(), '\\', '/');
