### ISSUE TITLE
Origin Shifting and XR bug

### ISSUE THREAD

**Issue by pinglis** [CesiumGS/cesium-unity#168]
If you following the instructions for enabling origin shifting when using an XR headset, the map falls away as if gravity was applied to it.  The instructions work fine for a non-xr camera.

These are the instructions i followed:

https://cesium.com/learn/unity/unity-placing-objects/

You can see it happen using the VR01_CesiumDeven scenario in the examples.  Just move the XR Origin to be under the CesiumGeoreference and attach the origin shift script to the Main Camera.

**Comment by Paul-Inglis** [comment]
Hi,

i've tested this again and can confirm that this is now working.  I'm not sure if something has been changed or if it was a documentation issue.

The current document says the following:

'Automatic origin shifting can be enabled by adding the CesiumOriginShift component to the main camera'

This should probably say:

'Automatic origin shifting can be enabled by adding the CesiumOriginShift component to the main camera or to the 'XR Origin' for VR.'

**Comment by kring** [comment]
Thanks for reporting back, @Paul-Inglis!
