### ISSUE TITLE
Create documentation on subscenes

### ISSUE THREAD

**Issue by argallegos** [CesiumGS/cesium-unity#171]
This should be a [cesium.com/learn](https://cesium.com/learn/) tutorial, and roughly the Unity equivalent of https://cesium.com/learn/unreal/unreal-sublevels/.

Topics to cover:
- Creating and managing georeferenced sub-scenes within the global scene.
- Filling each sub-scene with Unity assets.
- Understanding the difference between globe anchors and georeferenced sub-scenes.

**Comment by j9liu** [comment]
I think this can be closed now that the Unity [sub-scene tutorial](https://cesium.com/learn/unity/unity-subscenes/) is published!
