### ISSUE TITLE
Setting camera used for frustrum culling

### ISSUE THREAD

**Issue by petriw** [CesiumGS/cesium-unity#181]
Hi! Thank you for bringing this great asset to Unity developers.
I was curious if there are ways to change the camera used for frustrum culling, in runtime? (switching between internal cockpit views and external views)

Thank you!

**Comment by kring** [comment]
Thanks @petriw, glad you're enjoying Cesium for Unity.

Cesium uses [Camera.main](https://docs.unity3d.com/ScriptReference/Camera-main.html) to find the camera. From that documentation, it sounds like you should be able to tag all your cameras as "MainCamera" and then enable/disable them as appropriate.

Please let me know how that goes by following up in the [community forum](https://community.cesium.com/c/cesium-for-unity/13). We try to reserve github issues for bug reports and specific feature requests.
