### ISSUE TITLE
Allow user to set the "layer" of a Cesium3DTileset, and put all created tiles in the same layer

### ISSUE THREAD

**Issue by puos** [CesiumGS/cesium-unity#192]
I want to change unity layer of 3dtiles because of avatar collision and camera manipulation, but I don’t know how. ㅠㅠ

**Comment by j9liu** [comment]
Hi @puos,

Unforutnately, we don't currently support changing the Unity layer of 3D Tiles. I'll mark this as an enhancement so the team can revisit and potentially implement this in the future.
