### ISSUE TITLE
App crashes if cesium object is in scene on reloading scene

### ISSUE THREAD

**Issue by jolly17ify** [CesiumGS/cesium-unity#203]
Hi

I implemented Cesium in an existing VR app. It runs fine but when I reload scene, my app crashes. The reason of crash is cesium only as if I just remove the cesium object from my scene, the app runs fine.

**Comment by kring** [comment]
Can you tell us more about the crash? What's in the call stack? How are you reloading? Can you reproduce this in the Cesium for Unity Samples project as well, or only in your own?
