### ISSUE TITLE
Load a model at exact longitude and latiude 

### ISSUE THREAD

**Issue by italhaali** [CesiumGS/cesium-unity#216]
I want to load model from reources folder i want it to load at its exact latitude and longitude? can someone tell how to do it

**Comment by j9liu** [comment]
Hi @italhaali,

We use Github solely for bug-tracking and feature requests. In the future, please post questions like these on the [community forum](https://community.cesium.com/c/cesium-for-unity/13).

If you want to position a model at a certain longitude and latitude, you can attach a `CesiumGlobeAnchor` component and specify its global position.

**Comment by italhaali** [comment]
i am using resources.load to load from source folder, can u guide a little bit how to get access from global anchor at runtime to get exact longitude and latitude i provide a runtime
