### ISSUE TITLE
cesiumforunity is already support 3dtiles next?

### ISSUE THREAD

**Issue by GaryGaryGary** [CesiumGS/cesium-unity#242]
cesium icon 775877 in sandcastle is success,
but in unity,i cann`t get param "featureID"

**Comment by kring** [comment]
Please post questions to the [community forum](https://community.cesium.com/c/cesium-for-unity/13). GitHub issues are for confirmed bugs and specific feature requests.

Cesium for Unity supports some - but not all - of 3D Tiles v1.1. In particular, it currently only supports batch tables (e.g. in the older 3D Tiles 1.0 formats like b3dm) and the `EXT_feature_metadata` extension. We definitely plan to improve this before long.

**Comment by kring** [comment]
Here is the issue for adding support for the 3D Tiles 1.1 extension, `EXT_mesh_features`:
https://github.com/CesiumGS/cesium-native/issues/407
