### ISSUE TITLE
Create 2D Table Map

### ISSUE THREAD

**Issue by apettina** [CesiumGS/cesium-unity#247]
Is there a way to use Cesium to create a 2D map on a table in Unity, or is it only possible to make a globe right now?

**Comment by kring** [comment]
Please post questions to the [community forum](https://community.cesium.com/c/cesium-for-unity/13). We use github issues for bug reports and feature requests.

Cesium for Unity does not support 2D maps, and likely never will. Putting a section of the 3D globe on a flat table is possible, though. The trick is to provide a custom material that clips that tileset to the table edges.

**Comment by apettina** [comment]
Thanks for the heads up! I'll make sure to use the community forum going
forward.
