### ISSUE TITLE
Resources.Load cause invalid specify cast exception when experimental package VectorGraphic is imported

### ISSUE THREAD

**Issue by tainguyen7696** [CesiumGS/cesium-unity#251]
CesiumEditorStyle.cs line 48 
Texture2D icon = (Texture2D)Resources.Load(resourcePath);
change to:
Texture2D icon = Resources.Load<Texture2D>(resourcePath);
will get rid of this issue

**Comment by j9liu** [comment]
Hey @tainguyen7696,

Does `Resources.Load<Texture2D>(resourcePath)` raise an exception as well? Or does it work?

**Comment by tainguyen7696** [comment]
It does not raise exception. it should work
