### ISSUE TITLE
xyz map tiles format "https://someurl/sometilelayer{z}/{x}/{y}.png not loading Cesium Tile Map Service

### ISSUE THREAD

**Issue by techmavengeospatial** [CesiumGS/cesium-unity#262]
We are getting Unsupported Host or other errors when trying to connect to on-premises tile server
when we try real valid tile numbers instead of placeholders in the browser it returns images no problem
We've tried a bunch of Tile layers but can't get any of them to load
is there a trick for loading basemaps and overlay XYZ Raster Tiles?

**Comment by techmavengeospatial** [comment]
What is the Alternative?
We can also deliver OGC WMTS or WMS?  Are these supported?

**Comment by kring** [comment]
WMS and TMS are supported.

**Comment by kring** [comment]
What did you try? You'll want to create a CesiumTileMapServiceRasterOverlay component and add it to the same GameObject as the Cesium3DTileset that you want to drape it over.
