### ISSUE TITLE
basemap and overlay raster tiles (OGC WMTS)

### ISSUE THREAD

**Issue by techmavengeospatial** [CesiumGS/cesium-unity#263]
How can I load Basemap and/or Overlay Raster Map Tiles (I was told TMS and XYZ URL's are not supported)
is OGC WMTS URL's Supported?

If not what's the alternative for loading a tile layer?

**Comment by kring** [comment]
Please post of the [community forum](https://community.cesium.com/c/cesium-for-unity/13). We use GitHub issues exclusively for bug reports and feature requests.

TMS and WMS are already supported. Adding others, like WMTS, is a relatively easy contribution for a keen developer outside the Cesium team.
