### ISSUE TITLE
Documentation for TMS url

### ISSUE THREAD

**Issue by Techmaven-geospatial** [CesiumGS/cesium-unity#266]
If TMS is supported can I get an example.
It's just Y-row Flipped compared to XYZ.

ZOOM LEVEL ONE ORIGIN OF the Tiles OF the ROW/Y for TMS is lower left versus XYZ upper left .

I've tried about 30 tile URL's
If TMS was supported then It should have worked just showed my tiles in not right order.

Do you have any samples showing TMS ?

Many mapping apps support {-y} or 
 {ReverseY} Or TMS Is true/false
To handle difference
Cesiumjs WebGL does this with it's URLTemplate

**Comment by j9liu** [comment]
We do support TMS and WMS, but not with the URL template format. You should be able to use a valid URL to a `.xml` file and have it load with the `CesiumTileMapServiceRasterOverlay` component.

Please use the [community forum](https://community.cesium.com/) for these kinds of questions. We use our Github issues for bug tracking and feature requests.
