### ISSUE TITLE
Tileset Clipping Plane / Box

### ISSUE THREAD

**Issue by TuomasK1989** [CesiumGS/cesium-unity#286]
Hi I would like to make a clipping plane and box effect so that i could hide every pixel if the pixel is getting clipped. I have a unlit shader which works with Unity standard render pipeline and with static meshes but now I would like to get this to work with streamed 3d tileset data. Is there a way to assign a custom shader or material into instantiated 3d tiles in Unity and how should I modify my shader to work with 3d tileset? Or in general: What would be the best way to achieve this?

**Comment by j9liu** [comment]
Please post questions like this on the [community forum](https://community.cesium.com/). We use Github exclusively for bug tracking and feature requests.

You can take a look at the tile excluder example in this PR: https://github.com/CesiumGS/cesium-unity/pull/248
