### ISSUE TITLE
A lot of errors when instaling from disc to Unity

### ISSUE THREAD

**Issue by bakalarczuk** [CesiumGS/cesium-unity#292]
A lot of "must have an implementation part because it has accessibility modifiers." and " The type or namespace name 'ReinteropNativeImplementationAttribute' could not be found" when installed in project with PM but not from scoped registries but from local filesystem

**Comment by bakalarczuk** [comment]
Solved

**Comment by DivDev93** [comment]
> Solved

Hi Do you recall how you solved this? I'm having the same issue atm
