### ISSUE TITLE
New Input System Package Warning popup

### ISSUE THREAD

**Issue by Champi67** [CesiumGS/cesium-unity#301]
Hello,

It looks like since the last upgrade of cesium 1.1.0, i've this popup when opening our Unity project.
Do you've changed something on your side about this ?
![cesium](https://user-images.githubusercontent.com/124343882/235851947-8c74629b-2180-4369-87f7-49e0e80b016d.PNG)

**Comment by j9liu** [comment]
Please post questions like these on the [community forum](https://community.cesium.com/). We reserve Github for confirmed bugs and feature requests.

We added the InputSystem package as a dependency so people would stop seeing compiler errors about not having it in their project. You can always revert to the legacy input system for your own needs. In the future, you can see the full change log for the newest release [here](https://github.com/CesiumGS/cesium-unity/releases/tag/v1.1.0).

**Comment by Champi67** [comment]
Ohh ok
> Please post questions like these on the [community forum](https://community.cesium.com/). We reserve Github for confirmed bugs and feature requests.

It is not about not knowing how to change from New to Old input system. It is annoying to have this popup when the project is still using the old input system.
> We added the InputSystem package as a dependency so people would stop seeing compiler errors about not having it in their project. You can always revert to the legacy input system for your own needs. In the future, you can see the full change log for the newest release [here](https://github.com/CesiumGS/cesium-unity/releases/tag/v1.1.0).

But thanks for answering
