### ISSUE TITLE
TMS + WMS raster overlay overlapping is flikering

### ISSUE THREAD

**Issue by tomlee-dev** [CesiumGS/cesium-unity#304]
Hi.

I found that TMS(Cesium Tile Map Service Raster Overlay) + WMS(Cesium Web Map Service Raster Overlay) overlapping is flikering by camera distance.

I also read the article below. I checked Cesium Ion Raster Overlay + WMS is working fine on Cesium Unity latest (v1.1.0)

https://community.cesium.com/t/examples-of-wms-tms-raster-overlays/22683

I wonder if there is any option for it i missed or this is a bug

**Comment by kring** [comment]
Please ask questions on the [community forum](https://community.cesium.com/c/cesium-for-unity/13). We use github issues for bug reports and feature requests.

I don't know of any reason that TMS and WMS with translucency wouldn't work. But drop into the community forum and tell us more about your setup and what you're seeing and maybe we can help.

**Comment by tomlee-dev** [comment]
@kring Sorry~
I posted a thread in community forum.
https://community.cesium.com/t/tms-wms-raster-overlay-overlapping-is-flikering/23904
Thanks~!
