### ISSUE TITLE
Unable to retrieve mesh filters at runtime

### ISSUE THREAD

**Issue by zacmarvin** [CesiumGS/cesium-unity#309]
I'm trying to run GetObjectsOfType<MeshFilter> and it's returning 0 objects even though i see all the .b3dm files and there corresponding game objects with mesh filter components in the heirarchy. Is there some sort of limitation with Unity or Cesium for retrieving MeshFilters that are created at run time? When I add a primitive object to my scene and run the same script it returns that mesh filter so I don't believe its my script.

**Comment by j9liu** [comment]
Please use the community forum for posting questions like these. We reserve Github for confirmed bug reports and feature requests.

I see that you have already posted this to the forum, so we'll respond there.
