### ISSUE TITLE
Registry to install the Unity package from

### ISSUE THREAD

**Issue by hybridherbst** [CesiumGS/cesium-unity#312]
Right now, one has to download the .tgz (150 MB) and reference locally to get the package working. This also means that 150 MB go into source control or everyone working on a project needs to manually re-download the .tgz.

Would it be possible to release Cesium for Unity as package from a registry? This would allow referencing it directly from manifests without the heavy hit.

Such registries could be OpenUPM or custom ones.

**Comment by shehzan10** [comment]
@hybridherbst Cesium for Unity is already shipped as a package. See step 4 of https://cesium.com/learn/unity/unity-quickstart/#step-1-create-a-new-project-and-import-the-cesium-for-unity-package.

You can also see https://github.com/CesiumGS/cesium-unity-samples for an example of using the package.

**Comment by hybridherbst** [comment]
Ah, that's great! Then I was misguided by Google's guide here: https://developers.google.com/ar/geospatialcreator/unity/quickstart#add_required_dependencies which points at the tgz, while a package from the registry would be much more convenient. Thanks a lot!
