### ISSUE TITLE
Adding a Dynamic Camera shows 'Missing (Mono Script)' (HDRP)

### ISSUE THREAD

**Issue by csciguy8** [CesiumGS/cesium-unity#322]
Install Unity Hub 3.4.2 and Unity 2021.3.25f1.

Follow the 'Cesium for Unity Quickstart" guide,
https://cesium.com/learn/unity/unity-quickstart/

1. When creating the new project, use the "3D Sample Scene (HDRP)" template.
2. When installing Cesium from the Package Manager, use "Cesium for Unity, Version 1.2.0 - May 09, 2023"
3. Continue with the tutorial until you add a Dynamic Camera.

In the Inspector Window, you'll see a Script component that shows a warning icon and "Missing (Mono Script)". From a user perspective, I don't know if there is broken functionality or if I have set something up wrong.

When reproducing the same steps, but using the "3D Sample Scene (URP)" template, everything looks fine. Instead of the missing script, I see a "Universal Additional Camera Data" script.

**Comment by j9liu** [comment]
This would involve removing the "Universal Additional Camera Data" script from the prefab, so that the camera isn't tied to any one render pipeline.

**Comment by j9liu** [comment]
Note: The above would have to be done in a built-in render pipeline project, so that Unity doesn't automatically re-add the component to the camera. 🙃
