### ISSUE TITLE
No Environment Lighting in CesiumDefaultTileset Shader

### ISSUE THREAD

**Issue by timcreatedit** [CesiumGS/cesium-unity#341]
When using the `CesiumDefaultTilesetMaterial` on a tileset, shadows are always completely black. The Material doesn't seem to be affected by environment lighting from the Lighting Settings window.
![Screenshot 2023-06-30 at 22 38 33@2x](https://github.com/CesiumGS/cesium-unity/assets/42270125/fab9be0b-1450-486c-a56c-7858fdfaf3ae)

**Comment by timcreatedit** [comment]
It seems to be due to the way Ambient Occlusion is set up in the shader, it ends up with a value of 0  if there are no textures

**Comment by j9liu** [comment]
#337 addresses this issue, and it has been merged into main. Feel free to try the changes now, or wait until the upcoming release. Let us know if the issue still persists.
