### ISSUE TITLE
KTX2 tileset rendering problem

### ISSUE THREAD

**Issue by TuomasK1989** [CesiumGS/cesium-unity#346]
Hi,

I tried cesium-unity-samples version1.4 with KTX2 compressed tileset and got the following checkerboard error. Increasing maximum screen space error into 32 decreased checkerboard area and decreasing maximum screen space error into 8 made almost whole model to look checkerboard. Might there be something wrong in the tileset or code considering finest lod level handling?

![image](https://github.com/CesiumGS/cesium-unity/assets/61577660/bfac028e-afcf-45c5-87d4-ce3476da1662)

**Comment by kring** [comment]
Can you share the tileset with us so we can take a look? Am I right in thinking it worked in Cesium for Unity v1.3.1?

**Comment by TuomasK1989** [comment]
I have not tested in Cesium for Unity v1.3.1. In which email can I sent a link to tileset? I can not share this data into public use.

**Comment by kring** [comment]
You can send it to kevin@cesium.com. Thanks!

**Comment by TuomasK1989** [comment]
Thanks, I sent You email including the link to the data that is acting same way than in my first post. Hope it helps!

**Comment by kring** [comment]
Thanks for sending your tileset! I just opened a draft PR with a preliminary fix:
https://github.com/CesiumGS/cesium-unity/pull/347

You can try it out by going to Checks and then "Cesium for Unity, on: push". When the build is complete, you'll see a "Combined" artifact. Download that, extract the .tgz file from there, and install it with the Unity Package Manager.

**Comment by TuomasK1989** [comment]
Hi, It seems to work with couple of different ktx2 compressed and non compressed tilesets.
