### ISSUE TITLE
Check if XCode Project can build iOS app in CI

### ISSUE THREAD

**Issue by joseph-kaile** [CesiumGS/cesium-unity#357]
The current CI process only verifies if Unity can export the XCode project, but not if the XCode project can build the iOS app. This has caused problems when adding external projects (Zlib and meshoptimizer) that need to be included in the Unity CMakeFile. The issue is to find a way for CI to detect and report any errors in the XCode project before users try to build the iOS app on their Macs.

**Comment by kring** [comment]
Fixed in #363.
