### ISSUE TITLE
Google Map tiles are not rendering properly in the Editor's Scene View

### ISSUE THREAD

**Issue by RyuuyaS** [CesiumGS/cesium-unity#371]
Hello, I have a problem with the Unity Editor when it's rendering the Map tiles. In this coordinate(21.0675660418165, 105.811651485616), the object is rendered as a flat canvas and doesn't have any detail. While in this coordinate(39.736401, -105.25737), the object is rendered perfectly. In the [troubleshooting](https://developers.google.com/ar/geospatialcreator/unity/quickstart#map_tiles_are_not_rendering_properly_in_the_editors_scene_view) has this problem, it said about the shader but I check the package manager and it's already installed.

<img width="583" alt="image" src="https://github.com/CesiumGS/cesium-unity/assets/85359791/81565b1b-76e6-4a6e-ace0-de746537c6e4">
 
<img width="583" alt="image" src="https://github.com/CesiumGS/cesium-unity/assets/85359791/4aad8dd7-3239-45af-97da-4f36f294021b">

**Comment by kring** [comment]
Google most likely doesn't have any 3D data in that location (other than a terrain surface). You can confirm this by checking in Google Maps or Google Earth.
