### ISSUE TITLE
Compilation error missing DotNet

### ISSUE THREAD

**Issue by maki0315** [CesiumGS/cesium-unity#372]
![image](https://github.com/CesiumGS/cesium-unity/assets/62171024/5f727f38-1284-4cd1-bd8a-4a8db7d8aa2f)

**Comment by links-cyber** [comment]
@maki0315 I have the same issue, may I ask how did you fix it?

**Comment by links-cyber** [comment]
Now I figured it out, after running `dotnet publish Reinterop~ -o .`, I totally missed the line "open cesium-unity-samples project in the Unity Editor" from the docs
