### ISSUE TITLE
How to style 3D tiles like in CesiumJS?

### ISSUE THREAD

**Issue by whisper-bye** [CesiumGS/cesium-unity#375]
How to style 3D tiles like in CesiumJS?
https://cesium.com/learn/cesiumjs-learn/cesiumjs-3d-tiles-styling/

**Comment by csciguy8** [comment]
Hi @whisper-bye, please use our forum for questions like this,
https://community.cesium.com/c/cesium-for-unity/13

The community could have some great ideas, or will have answered this in the past.

Thanks
