### ISSUE TITLE
create release package of Cesium for Unity failed.

### ISSUE THREAD

**Issue by lijuhong1981** [CesiumGS/cesium-unity#376]
I use "dotnet run --project Build~" commnd create release package of Cesium for Unity,  
it print's log "RenderTexture.Create with shadow sampling failed: Hardware does not support shadow compare sampling."，
then the release failed.
![20231101090020](https://github.com/CesiumGS/cesium-unity/assets/3949154/77fb3ca6-332e-4ec8-bb21-aa4b422b5c9e)
How to solve this problem?
my computer：
OS：windows10 22H2 x64
CPU：Intel(R) Core(TM) i9-9900K
RAM：64G
GPU：NVIDIA Geforce RTX 2080Ti  12G
Unity Version：2021.3.10f1c2

**Comment by kring** [comment]
I think that message is probably unrelated to the failure. It looks like it failed while compiling for UWP. Are you set up with the necessary build toolset for UWP? If not, and you don't need UWP, you could just comment out t that part of the process.

**Comment by lijuhong1981** [comment]
I don't need UWP，how to remove UMP of the process？

**Comment by kring** [comment]
Just comment out the lines in the Package.cs file:
https://github.com/CesiumGS/cesium-unity/blob/5c5376517722b0e3fe8fad007855b84a0cd1c3da/Build~/Package.cs#L148

I'm going to close this issue. If you have followup questions, post them to the community forum:
https://community.cesium.com/c/cesium-for-unity/13

**Comment by lijuhong1981** [comment]
ok, thanks！
