### ISSUE TITLE
cesium unity ar geospatial

### ISSUE THREAD

**Issue by ys1317** [CesiumGS/cesium-unity#377]
i got this alirt pleace help me
![geospatial ar tour - new - Android - Unity 2021 3 30f1 Education _DX11_ 11_6_2023 2_35_29 PM](https://github.com/CesiumGS/cesium-unity/assets/83608810/ddeaa121-e5d0-4064-ac5a-76b76f390aa2)
![geospatial ar tour - new - Android - Unity 2021 3 30f1 Education _DX11_ 11_6_2023 2_35_51 PM](https://github.com/CesiumGS/cesium-unity/assets/83608810/9488018f-c2f8-4ea4-bc1e-105033030a8e)
![geospatial ar tour - new - Android - Unity 2021 3 30f1 Education _DX11_ 11_6_2023 2_35_57 PM](https://github.com/CesiumGS/cesium-unity/assets/83608810/fe51e8d2-3e67-4b58-8aad-6ca707cc31a5)

**Comment by j9liu** [comment]
We can't help you without more information. What versions of Unity Editor and Cesium for Unity are you using? How did you set this project up? Walk us through what you did, step-by-step, so we can reproduce the error.

**Comment by kring** [comment]
Please post the further information @j9liu requested to the [community forum](https://community.cesium.com/c/cesium-for-unity/13). We use GitHub for confirmed bugs and concrete feature requests.

**Comment by ys1317** [comment]
versions of Unity Editor 2021.3.30f 
 and Cesium for Unity 1.3.0
How did iset this project up : 
1. Open the AR project.
2. Add an AR extension.
3. Add the Cesium package.
4. In the Unity hierarchy, add the AR GeoSpatialOrigin.
5. In the Inspector and under `Edit > Project Settings > XR Plug-in Management > ARCore Extensions > Android Authentication Strategy`, add the Android API key.
6. Check the Geospatial option under `Edit > Project Settings > XR Plug-in Management > ARCore Extensions > Optional Features > Geospatial`.
7. Add a 3D object and attach the ARGeoSpatialAnchorCreator component to it.
8. Add the CesiumGeoreference component to the Unity hierarchy.

9. Add the Cesium Camera Controller, Cesium Origin Shift, and Cesium Global Anchor to the AR camera in the Unity hierarchy.
And also, I added Cesium World Terrain because Cesium 3D Tileset didn't work, so I kept both.
@j9liu

**Comment by kring** [comment]
Please try upgrading to the latest version (v1.6.4). v1.3.0 is quite old, and v1.3.1 in particular fixed a problem on iOS that may be what you're seeing above.

If you still have trouble after upgrading, please post to the [community forum](https://community.cesium.com/c/cesium-for-unity/13) and include as much detail as you can about what is going wrong. Warnings in the Console are not necessarily a problem, unless they're also causing something else to break.

**Comment by yasmeennof** [comment]
![geo t - SampleScene - Android - Unity 2021 3 30f1 Education _DX11_ 11_7_2023 12_34_06 PM](https://github.com/CesiumGS/cesium-unity/assets/144335343/bbc32f05-a91e-43a9-aed4-008a13db1bb7)
 this what i git after adding the Cesium for Unity v1.6.4

**Comment by kring** [comment]
How did you add it? It looks like you might have added the source code from GitHub rather than the built package.
