### ISSUE TITLE
encounter some problems while using Cesium for Unity

### ISSUE THREAD

**Issue by linglom1** [CesiumGS/cesium-unity#381]
Hello Developer, I am encountering some problems while using Cesium for Unity. When I load a 600MB OBJ model into the Unity-built model, operating this model is very smooth. However, when I render the corresponding 3D Tiles model using Cesium for Unity, there is a significant delay in operation. For example, when I rotate the model, the response is quite slow. This confuses me, and I am eager to get your answer. I wish you a pleasant life.

**Comment by csciguy8** [comment]
Hi @linglom1 , would you mind posting this question in our forum?

https://community.cesium.com/c/cesium-for-unity/13

That's the best place for general usage questions, and you may find others who have had similar problems.
