### ISSUE TITLE
CesiumCreditSystem destroys itself when an additive scene is unloaded

### ISSUE THREAD

**Issue by TobiasWehrum** [CesiumGS/cesium-unity#436]
My main scene uses Cesium to show a map and occasionally loads additional Unity scenes (that have nothing to do with the Cesium content) in additive mode. When one of those unrelated additive scenes is unloaded the CesiumCreditSystem destroys itself, leaving my scene without credits.

**Comment by j9liu** [comment]
Thanks for the report @TobiasWehrum ! I just opened #445 to address this issue. Feel free to try it out and let us know if it addresses this, or if you still experience any problems.
