### ISSUE TITLE
3Dtile is at the wrong place

### ISSUE THREAD

**Issue by ThomasBillaud2** [CesiumGS/cesium-unity#443]
Hello,

I've made a custom 3DTile from an obj file with Obj2Tiles but when placed on the globe, the mesh is actually thousands of kilometers away from the origin.

How the tileset appears on the scene view :
![image](https://github.com/CesiumGS/cesium-unity/assets/164381850/9f7d08a8-7f7c-4d4d-8212-aca2b514583a)

Position of an object created nearby the mesh :
![image](https://github.com/CesiumGS/cesium-unity/assets/164381850/f7276071-18f7-40d0-b316-200127298004)

It seems to be caused by a difference between the CRS used for the obj file and the one used by Cesium.
Is there any other CRS supported by Cesium on Unity other than ECEF ?

**Comment by csciguy8** [comment]
Hi @ThomasBillaud2 , would you mind asking these kinds of usage question on our forum?

https://community.cesium.com/c/3d-tiles/16
https://community.cesium.com/c/cesium-for-unity/13

(also, it may have already been asked)

Thanks!
