### ISSUE TITLE
Error Scaling map on magic leap 2

### ISSUE THREAD

**Issue by GiannisApost** [CesiumGS/cesium-unity#453]
I am trying to scale down the entire map in my magic leap 2 project but as soon as i change the scale value i get this error
![image](https://github.com/CesiumGS/cesium-unity/assets/79788413/f207bdbc-2cf3-4454-9915-4938dd17d3a8)

![image](https://github.com/CesiumGS/cesium-unity/assets/79788413/be773e50-8d4c-46f0-b257-22109f9a81b4)

**Comment by j9liu** [comment]
Hi @sdi1900012, sorry for the delay in getting to this.

It looks like that "Step Offset" bug isn't related to Cesium code. What does it correspond to? Can you double-click on the error and show us the line of code that is failing?

**Comment by j9liu** [comment]
@GiannisApost it's been a while since we saw activity on this post, so I'm closing this issue. If this is still affecting you, please reopen with more information. Thank you!
