### ISSUE TITLE
Some Ion imagery assets attempt to load from localhost instead of the correct URLs

### ISSUE THREAD

**Issue by azrogers** [CesiumGS/cesium-unity#455]
[As identified on the forums](https://community.cesium.com/t/unable-to-use-bing-maps-labels-only-raster-overlay/31497), Cesium for Unity (and potentially all cesium-native clients) attempts to load some Ion imagery overlays from the incorrect URLs. For example, for asset 2411391, the request to the Ion endpoint gives:
```
{
    "type": "IMAGERY",
    "externalType": "BING",
    "options": {
        "url": "//dev.virtualearth.net",
        "mapLayer": "Foreground",
        "mapStyle": "AerialWithLabelsOnDemand",
        "key": "<key removed>"
    },
    "attributions": [...]
}
```

Based on this information, Cesium for Unity should calculate the URL `https://dev.virtualearth.net/REST/v1/Imagery/Metadata/AerialWithLabelsOnDemand?incl=ImageryProviders&key=<key removed>&uriScheme=https`, as CesiumJS does. Instead it tries to make a request for the URL `http://localhost/REST/v1/Imagery/Metadata/AerialWithLabelsOnDemand?incl=ImageryProviders&key=<key removed>&uriScheme=https`, which obviously fails.

**Comment by j9liu** [comment]
@azrogers is this fixed as of https://github.com/CesiumGS/cesium-native/pull/864?
