### ISSUE TITLE
Water Tiles suddenly go up when getting close, leaving a big gap to see under the map.

### ISSUE THREAD

**Issue by electrum-bowie** [CesiumGS/cesium-unity#461]
I'm using the latest cesium for unity package, and this happens in lots of areas, like in the waters between Manhattan and Statue of Liberty, but i encountered the issue again at the Golden Gate Bridge, which made it easier to see in a recording :

https://github.com/CesiumGS/cesium-unity/assets/88616437/9ed2bf32-c9b6-4654-8cfc-6b1638ee7d9e

Not sure if it happens everywhere, but at least at these two areas it seems it happens everytime i go there and stay longer..

**Comment by kring** [comment]
Which tileset are you using? It's most likely a data problem rather than a bug in Cesium for Unity, but with a bit more information we can confirm that.

**Comment by electrum-bowie** [comment]
Photorealistic Google Map Tiles

**Comment by kring** [comment]
And where is that video recorded? You said Golden Gate Bridge, but your video doesn't look to me anything like the Golden Gate Bridge in San Francisco.

**Comment by kring** [comment]
Here's a gap in the same location in Google Maps (the blue):
![image](https://github.com/CesiumGS/cesium-unity/assets/924374/2f18b837-e376-4456-b601-82dca4becad9)
