### ISSUE TITLE
Abnormal display of oblique photography point cloud data

### ISSUE THREAD

**Issue by luolihui119** [CesiumGS/cesium-unity#472]
the oblique photography has point cloud data and B3dm, pnts display has problem. Display normal in cesiumjs.
May I ask what needs to be done?

![1719371873492](https://github.com/CesiumGS/cesium-unity/assets/18692344/339db939-df59-4102-97ce-29c5ffd94b9d)

The cesiumjs display is as follows:

![1719371929517](https://github.com/CesiumGS/cesium-unity/assets/18692344/af228dc1-55ce-4728-8ffc-0462b3e880ad)

**Comment by kring** [comment]
I'm not sure what might cause that. What version of Cesium for Unity are you using? And how was the tileset produced? Can you share this tileset with us? Or another one that has the same problem?

**Comment by j9liu** [comment]
HI @luolihui119,

We've seen similar issues on the community forum before, often with point clouds produced by cesiumlab (which is not actually affilated with Cesium). If that is the case, I would recommend tiling with [Cesium ion](https://cesium.com/platform/cesium-ion/) instead and testing the result. 

Of course, if you see this behavior with a point cloud that _has_ been produced by Cesium ion, let us know.
