### ISSUE TITLE
CesiumCreditSystem NotImplementedException: The native library is out of sync with the managed one. 

### ISSUE THREAD

**Issue by kkkarannn** [CesiumGS/cesium-unity#483]
When building Cesium For Unity from source for AVP. 
Getting NotImplementedException Errors when building the package 

`NotImplementedException: The native library is out of sync with the managed one. `
<img width="751" alt="Screenshot 2024-07-30 at 3 22 48 PM" src="https://github.com/user-attachments/assets/8a2c5017-ca17-4a17-a3b2-18d37a7761a0">

**Comment by kring** [comment]
Apple Vision Pro is not a supported platform. If you're doing some work to get it going, that's great! But you should a) share that work with the community, and b) discuss problems you run into on the [community forum](https://community.cesium.com/c/cesium-for-unity/13). If you're just hitting compile and hoping for the best... well, that's probably not going to work. This thread may be helpful: https://community.cesium.com/t/cmake-not-found-cesium-unity-for-visionos/32634
