### ISSUE TITLE
Apple Vision Pro Support

### ISSUE THREAD

**Issue by demonixis** [CesiumGS/cesium-unity#485]
Hello,
Is it possible to enable Apple Vision Pro support? After looking at the code, it seems that you "just" have to make a VisionOS folder with compiled libs in it. If you have a doc to build dependencies I can try to do it by myself.
I was not able to find an entry point when libraries are loaded, just `[DllImport("CesiumForUnityNative-Runtime", CallingConvention=CallingConvention.Cdecl)]` lines like that. So I guess just copying libs and select VisionOS as target will be fine.

I've the headset, a Unity project that uses Cesium and that want to target VisionOS, so ready to test it.

**Comment by kring** [comment]
This has been discussed several times on the community forum:
* https://community.cesium.com/t/cmake-not-found-cesium-unity-for-visionos/32634
* https://community.cesium.com/t/cesium-for-unity-on-apple-vision-pro-xcode-build-errors/32132
* https://community.cesium.com/t/fail-to-build-release-package-of-cesium-for-unity-for-visionos/34112
