### ISSUE TITLE
CesiumPolygonRasterOverlay Cliping can not work when use HDRP

### ISSUE THREAD

**Issue by XudongZhou** [CesiumGS/cesium-unity#486]
I test in unity2022.3 and Unity6000,
The CesiumPolygonRasterOverlay  has the same bug.
CesiumPolygonRasterOverlay Can not Clip when use HDRP,but URP work fine.

**Comment by kring** [comment]
Thanks for the bug report @XudongZhou. Can you please confirm what version of Cesium for Unity you're using?

**Comment by luolihui119** [comment]
> Thanks for the bug report @XudongZhou. Can you please confirm what version of Cesium for Unity you're using?

the unity version is 2022.3.40,the Cesium for Unity version is 1.11.0;

The effect is as follows:

![1724382135833](https://github.com/user-attachments/assets/8792e6fa-3113-4dae-ba95-7d9a14fb3642)

![1724382135833](https://github.com/user-attachments/assets/c27cdd83-843e-498d-98d1-113aa021d9aa)

**Comment by luolihui119** [comment]
> I can't tell quite what I'm looking at in that screenshot. Is it correctly discarding whole tiles, but not clipping the ones that are partially inside the polygon? If that's the case, are you by any chance using a custom Material on this tileset? The clipping of partially-overlapping tiles is done by the Material.

1、No material assigned
![1724383109458](https://github.com/user-attachments/assets/69008163-11af-461a-8aff-b0cbda2ed64a)
2、The first screenshot shows that when the camera is zoomed in, some of the image blocks will be clipping.The second screenshot shows that when the camera is pulled away, it is not clipping

3、It's normal in URP：
![1724383753934](https://github.com/user-attachments/assets/0da475d6-5d47-4e0d-ad27-49d0273ad6e9)

**Comment by luolihui119** [comment]
> > Thanks for the bug report @XudongZhou. Can you please confirm what version of Cesium for Unity you're using?
> 
> the unity version is 2022.3.40,the Cesium for Unity version is 1.11.0;
> 
> The effect is as follows:
> 
> ![1724382135833](https://private-user-images.githubusercontent.com/18692344/360741994-8792e6fa-3113-4dae-ba95-7d9a14fb3642.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzODQzMzAsIm5iZiI6MTcyNDM4NDAzMCwicGF0aCI6Ii8xODY5MjM0NC8zNjA3NDE5OTQtODc5MmU2ZmEtMzExMy00ZGFlLWJhOTUtN2Q5YTE0ZmIzNjQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIzVDAzMzM1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMyOGVjM2VjN2EzNmE0NDFjMTFiMjU3MDVlMjBjMDA5ZmM2YjRmZjFhMmFhODQzZDJjYjQxYTBmMmUwNWM1ZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cw0gxpFawmFVQwLre7TKJphyazo8N9fhfqgqBCPY_7o)
> 
> ![1724382135833](https://private-user-images.githubusercontent.com/18692344/360741365-c27cdd83-843e-498d-98d1-113aa021d9aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzODQzMzAsIm5iZiI6MTcyNDM4NDAzMCwicGF0aCI6Ii8xODY5MjM0NC8zNjA3NDEzNjUtYzI3Y2RkODMtODQzZS00OThkLTk4ZDEtMTEzYWEwMjFkOWFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIzVDAzMzM1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4NTMxMjRkYjEzNGM5ZDNlMjAxZWNkNzUyMjdhODc5YzQzZTRhNWYzODJjZmZhOTZlNjQ1YTAyZjdhMmIwYTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1M-f6OJGJVlEeGFGOARFv2YGhHlXkAZeyAcdaEf6f5k)

sorry,there is a problem with the screenshot;

The blue line is spline.

![1724384259950](https://github.com/user-attachments/assets/4401c50c-c333-4a6d-a78f-e3e9fe988dfd)

![1724384190362](https://github.com/user-attachments/assets/070ef474-aca3-4d97-9c8c-9eaadd3c6355)

**Comment by kring** [comment]
Yeah that behavior is consistent with the _tile_ exclusion working correctly, but the material-based _pixel_ exclusion not working. In other words, there is something wrong with the Material in HDRP. It could be as simple as "Alpha Clipping" is disabled on the HDRP material. I will investigate when I get a chance.

**Comment by XudongZhou** [comment]
Yeah I copy the "CesiumDefaultTilesetShader" and change "Alpha Clipping" to enabled, then worked fine in HDRP.

**Comment by XudongZhou** [comment]
Yeah I copy the "CesiumDefaultTilesetShader" and changed "Alpha Clipping" to enabled, then create a material with it instead of the default material in Cesium3DTileset component, worked fine in HDRP.
