### ISSUE TITLE
CMakeLists.txt changes needed to build on RHEL8.6

### ISSUE THREAD

**Issue by whowe444** [CesiumGS/cesium-unity#506]
It seems like the generated code that gets created after exporting the Reinterop package and re-opening Unity expects C++20. This is not explicitly clear in the top CMakeLists.txt file. I found that in order to get this to build on RHEL8.6 I needed add the following lines to the top CMakeLists.txt file.
```
set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_BUILD_TYPE debug)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++20")
```
Perhaps I am doing something wrong, or have a misunderstanding. But would the project be open to adding these lines in the top-level CMakeLists.txt file?

Thanks

**Comment by kring** [comment]
Hi @whowe444, exactly what problem are you seeing without these lines? The individual libraries that include the generated code do set their target as C++20:
https://github.com/CesiumGS/cesium-unity/blob/v1.12.0/native~/Runtime/CMakeLists.txt#L53
https://github.com/CesiumGS/cesium-unity/blob/v1.12.0/native~/Editor/CMakeLists.txt#L44

Perhaps you have some other project that is `#include`'ing generated code, and that project is not set to target C++20?

**Comment by whowe444** [comment]
@kring I was following the tutorial in developer-setup.md... so I didn't have any other code. Can post more detailed compile errors tomorrow.

**Comment by whowe444** [comment]
Ok @kring looks like you are right. I don't need CMakeLists.txt changes.. I guess I would suggest some additional notes in the developer-setup.md documentation since it doesn't make note that you need a C++ compatible compiler:
```
export CC="/opt/rh/gcc-toolset-13/root/usr/bin/gcc"
export CXX="/opt/rh/gcc-toolset-13/root/usr/bin/g++"
cd cesium-unity-samples/Packages/com.cesium.unity/native~
cmake -B build -S . -DCMAKE_BUILD_TYPE=Debug -DVCPKG_TRIPLET="x64-linux"
cmake --build build -j14 --target install --config Debug
```

I'm finding that I need to add an additional arg for the VCPKG_TRIPLET and I also need to export those two env vars for the compiler (I needed an updated compiler version to be able to build the C++20 stuff).

**Comment by kring** [comment]
Ok, thanks for the update @whowe444. I updated the docs to mention C++20 in #508 (merging it will close this issue).

**Comment by whowe444** [comment]
Thanks for the help.
