### ISSUE TITLE
Ask questions about build

### ISSUE THREAD

**Issue by luolihui119** [CesiumGS/cesium-unity#510]
hello,I have some questions about build.

I have updated the latest code.

the environment:

    Visual Studio 2022

    cmake 3.29.2

    dotnet 8.0.400
Can you help me take a look，Thank You

Running command error：cmake -B build -S . -DCMAKE_BUILD_TYPE=RelWithDebInfo

![1727430858315](https://github.com/user-attachments/assets/e6a1d47e-c994-4860-888a-422cae7f6ac2)
![1727431036326](https://github.com/user-attachments/assets/a454610f-b18b-4e50-bddd-9ffeedf959bb)
![1727431223884](https://github.com/user-attachments/assets/6de9935c-2c1c-42c8-bc49-1d0bbe214b69)
![1727431450026](https://github.com/user-attachments/assets/7ab121df-8341-4b19-aaaa-acfc2c40692d)

**Comment by kring** [comment]
I think you may need to install bash. The easiest way to get it is by installing WSL or [Git for Windows](https://git-scm.com/downloads/win).

If that doesn't help, please post to the [community forum](https://community.cesium.com/c/cesium-for-unity/13). We use github issues for confirmed bugs and clear feature requests only.
