### ISSUE TITLE
Does the async asset buffer size have any impact on framerate ?

### ISSUE THREAD

**Issue by electrum-bowie** [CesiumGS/cesium-unity#533]
![image](https://github.com/user-attachments/assets/3c008c36-36bc-4168-a634-8574d8fb27cf)

Does the async asset buffer size in `PROJECT SETTINGS > QUALITY` have any impact on framerate when using Google's 3D Tiles ?

**Comment by kring** [comment]
Hi @electrum-bowie, please post questions to the [community forum](https://community.cesium.com/c/cesium-for-unity/13). We use GitHub issues exclusively for clear bugs and feature requests.

I'm not familiar with that setting, and I'm not aware of any way in which it would impact Cesium for Unity performance. Have you observed any difference when you change it?

**Comment by electrum-bowie** [comment]
Can i turn it off if memory is a priority ?
