### ISSUE TITLE
Question: Can Cesium3DTileset be always above the CesiumWebMapTileServiceRasterOverlay regardless of it's hight above sea level (where WMTS is higher than tileset)?

### ISSUE THREAD

**Issue by asafMasa** [CesiumGS/cesium-unity#542]
In my project, I have both Cesium3DTileset and CesiumWebMapTileServiceRasterOverlay 
In places where the absolute height (height above sea level) of the CesiumWebMapTileServiceRasterOverlay is higher than that of the "Cesium3DTileset",  I want to show only the "Cesium3DTileset" and ignore the CesiumWebMapTileServiceRasterOverlay - can it be done?

In this example, I've created a "hole" in the WMTS overlay around the 3D model but I would like it to be without 
![image](https://github.com/user-attachments/assets/4e313122-823c-463d-976d-b1a2b36b67be)

**Comment by kring** [comment]
@asafMasa please post questions to the [community forum](https://community.cesium.com/c/cesium-for-unity/13). We use GitHub for bug reports and clear feature requests.

I'm confused by your question because a `CesiumWebMapTileServiceRasterOverlay` is just images, it doesn't have any height at all.
