### ISSUE TITLE
Add support for RasterizedPolygonsTileExcluder

### ISSUE THREAD

**Issue by mwilsnd** [CesiumGS/cesium-unity#64]
Currently tile exclusion is not exposed to C#. Support for RasterizedPolygonsOverlay/RasterizedPolygonsTileExcluder enables extra optimizations for developers creating more confined game levels or AR experiences. Going the extra mile, support for C# implementations of ITileExcluder and the ability to provide these to TilesetOptions::excluders would provide maximum flexibility for custom culling logic without having to leave the C# environment.

**Comment by j9liu** [comment]
For the record, support for `ITileExcluder` implementations was added with #248, but we still don't support `RasterizedPolygonsTileExcluder` itself.

**Comment by XinDongDeXin** [comment]
Has this problem been solved now?

**Comment by XinDongDeXin** [comment]
Maps load until the system crashes, and it would be nice if there was a way to limit the load range.

**Comment by kring** [comment]
j9liu's comment above still represents the current state. The feature described in #248 should work pretty well for the use-case of limiting range.

But if normal map loading is leading to a system crash (out of memory?), then something is almost certainly wrong either with your settings or your tileset. Perhaps you've set the Maximum Screen Space Error too low? Or your tileset has too many tiles at even a low level of detail? Or the Maximum Cache Bytes is set too high for the available system memory? Keep in mind that the value represents the size of the tiles coming over the network; they can actually be significantly larger once resident in memory. Set it to 0 and see if the crash goes away.

**Comment by j9liu** [comment]
This should have been closed by #407 , closing now.
